version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_AUTHDATABASE}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: